{"app":"exunit_summarizer","classname":"Elixir.TestWithSummaryTest","describe":null,"describe_line":null,"failed":false,"file":"/Users/opalsymes/Solve/exunit-summarizer/test/exunit_summarizer_test.exs","line":20,"logs":"","message":"due to skip tag","name":"test one that skipped","skipped":true,"success":false,"test_type":"test","time":0.0}
{"app":"exunit_summarizer","classname":"Elixir.TestWithSummaryTest","describe":null,"describe_line":null,"failed":false,"file":"/Users/opalsymes/Solve/exunit-summarizer/test/exunit_summarizer_test.exs","line":8,"logs":"\u001B[33m[warn] This should not output\n\u001B[0m","name":"test one that passes","skipped":false,"success":true,"test_type":"test","time":0.001443}
{"app":"exunit_summarizer","body":"  0) test one that fails when MAKE_TESTS_FAIL != \"\" (TestWithSummaryTest)\n     \u001B[1m\u001B[30mtest/exunit_summarizer_test.exs:13\u001B[0m\n     \u001B[31mAssertion with == failed\u001B[0m\n     \u001B[36mcode:  \u001B[0massert @should_fail == \"\"\n     \u001B[36mleft:  \u001B[0m\"\u001B[31mthis test intentionally fails\u001B[0m\"\n     \u001B[36mright: \u001B[0m\"\u001B[48;5;28m\u001B[0m\"\n     \u001B[36mstacktrace:\u001B[0m\n       test/exunit_summarizer_test.exs:16: (test)\n","classname":"Elixir.TestWithSummaryTest","describe":null,"describe_line":null,"failed":true,"file":"/Users/opalsymes/Solve/exunit-summarizer/test/exunit_summarizer_test.exs","line":13,"logs":"\u001B[33m[warn] This should output.\n\u001B[0m\u001B[31m[error] This should show an error.\n\u001B[0m","message":"Assertion with == failed","name":"test one that fails when MAKE_TESTS_FAIL != \"\"","skipped":false,"success":false,"test_type":"test","time":0.001654}
{"app":"exunit_summarizer","classname":"Elixir.TestWithSummaryTest","describe":null,"describe_line":null,"failed":false,"file":"/Users/opalsymes/Solve/exunit-summarizer/test/exunit_summarizer_test.exs","line":24,"logs":"","name":"test slow test","skipped":false,"success":true,"test_type":"test","time":2.000491}
{"app":"exunit_summarizer","classname":"Elixir.TestWithSummaryTest","describe":"a describe block","describe_line":30,"failed":false,"file":"/Users/opalsymes/Solve/exunit-summarizer/test/exunit_summarizer_test.exs","line":31,"logs":"","name":"test a describe block one that passes","skipped":false,"success":true,"test_type":"test","time":7.0e-6}
{"app":"exunit_summarizer","body":"  0) test a describe block one that fails when MAKE_TESTS_FAIL != \"\" (TestWithSummaryTest)\n     \u001B[1m\u001B[30mtest/exunit_summarizer_test.exs:35\u001B[0m\n     \u001B[31mAssertion with == failed\u001B[0m\n     \u001B[36mcode:  \u001B[0massert @should_fail == \"\"\n     \u001B[36mleft:  \u001B[0m\"\u001B[31mthis test intentionally fails\u001B[0m\"\n     \u001B[36mright: \u001B[0m\"\u001B[48;5;28m\u001B[0m\"\n     \u001B[36mstacktrace:\u001B[0m\n       test/exunit_summarizer_test.exs:36: (test)\n","classname":"Elixir.TestWithSummaryTest","describe":"a describe block","describe_line":30,"failed":true,"file":"/Users/opalsymes/Solve/exunit-summarizer/test/exunit_summarizer_test.exs","line":35,"logs":"","message":"Assertion with == failed","name":"test a describe block one that fails when MAKE_TESTS_FAIL != \"\"","skipped":false,"success":false,"test_type":"test","time":3.3e-5}